{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [04/Dec/2019 15:30:54] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [04/Dec/2019 15:30:56] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [04/Dec/2019 15:30:56] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "[2019-12-04 15:30:56,368] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 2897, in get_loc\n",
      "    return self._engine.get_loc(key)\n",
      "  File \"pandas\\_libs\\index.pyx\", line 107, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\index.pyx\", line 131, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "KeyError: None\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 556, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 513, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-1-4486d6009484>\", line 54, in update_graphic\n",
      "    y=random_y[yaxis],\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\pandas\\core\\frame.py\", line 2980, in __getitem__\n",
      "    indexer = self.columns.get_loc(key)\n",
      "  File \"C:\\Users\\saila\\Anaconda3\\lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 2899, in get_loc\n",
      "    return self._engine.get_loc(self._maybe_cast_indexer(key))\n",
      "  File \"pandas\\_libs\\index.pyx\", line 107, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\index.pyx\", line 131, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "KeyError: None\n",
      "127.0.0.1 - - [04/Dec/2019 15:30:56] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [04/Dec/2019 15:31:01] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [04/Dec/2019 15:31:08] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [04/Dec/2019 15:31:22] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [04/Dec/2019 15:31:25] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import plotly.graph_objs as go\n",
    "import numpy as np\n",
    "from flask import Flask\n",
    "from dash.dependencies import Input, Output\n",
    "import pandas as pd\n",
    "\n",
    "server = Flask(__name__)\n",
    "app = dash.Dash(__name__, server=server)\n",
    "\n",
    "np.random.seed(101)\n",
    "random_x = np.random.randint(1,21,20)\n",
    "random_y = {'random_y1': np.random.randint(1,21,20),\n",
    "            'random_y2': np.random.randint(20,41,20)}\n",
    "random_y = pd.DataFrame(random_y)\n",
    "\n",
    "app.layout = html.Div(children=[\n",
    "    html.H1('Hello World'),\n",
    "    dcc.Dropdown(\n",
    "        id='yaxis',\n",
    "        options=[\n",
    "            {'label': 'Random List 1', 'value': 'random_y1'},\n",
    "            {'label': 'Random List 2', 'value': 'random_y2'}\n",
    "        ]),\n",
    "    dcc.Graph(\n",
    "        id='scatter',\n",
    "        figure={\n",
    "            'data':[\n",
    "                go.Scatter(\n",
    "                    x = random_x,\n",
    "                    y = [0,0],\n",
    "                    mode = 'markers'\n",
    "                )\n",
    "            ],\n",
    "            'layout':go.Layout(\n",
    "                title = 'Here is My Scatter Plot',\n",
    "                xaxis = {'title': 'Height'},\n",
    "                yaxis = {'title': 'Weight'}\n",
    "            )\n",
    "        })\n",
    "])\n",
    "\n",
    "#here is the callback\n",
    "@app.callback(\n",
    "    Output('scatter', 'figure'),\n",
    "    [Input('yaxis', 'value')])\n",
    "\n",
    "def update_graphic(yaxis):\n",
    "    return{\n",
    "        'data': [go.Scatter(\n",
    "            x=random_x,\n",
    "            y=random_y[yaxis],\n",
    "            mode='markers')],\n",
    "        'layout': go.Layout(\n",
    "            title='Here is another Scatter Plot{}'.format(yaxis),\n",
    "            xaxis={'title': 'Here is X-Axis'},\n",
    "            yaxis={'title': yaxis})\n",
    "    }\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
